// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozyzkeddhldosnxwrnok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96eXprZWRkaGxkb3NueHdybm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5OTQxMTIsImV4cCI6MjA1NjU3MDExMn0.UnLM7Ggbw_6PUxh_wfqfNd3WhugT1ljMnwUzP8vHGb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);